name: Deploy Laravel to VPS Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Build and deploy Docker container with docker-compose
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        # SSH into VPS
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF

          # Navigate to deployment directory
          cd /home/$VPS_USER || exit

          # Stop and remove old containers if they exist
          docker-compose down || true

          # Clone the repository
          git clone https://github.com/Quaniscoding/Library-management.git /home/$VPS_USER/laravel_app

          # Navigate to the Laravel app directory
          cd /home/$VPS_USER/laravel_app || exit

          # Build and start services using docker-compose
          docker-compose up -d --build

          # Run database migrations and seeds
          docker-compose exec app php artisan migrate --force
          docker-compose exec app php artisan db:seed --force

          # Clean up cloned repository
          cd ..
          rm -rf laravel_app

          # Clean up old Docker images
          docker image prune -f
        EOF
