name: Deploy Laravel to VPS Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Build and deploy Docker container with docker-compose
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        # SSH into VPS
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF

          # Navigate to the home directory
          cd /home/$VPS_USER || exit

          # Check if laravel_app directory exists, if yes, clean up
          if [ -d "/home/$VPS_USER/laravel_app" ]; then
            cd laravel_app || exit

            # Stop and remove old containers if they exist
            docker-compose down || true 

            # Clean up old cloned repository
            cd ..
            rm -rf laravel_app
          fi

          # Clone the repository into the laravel_app directory
          git clone https://github.com/Quaniscoding/Library-management.git /home/$VPS_USER/laravel_app

          # Navigate to the Laravel app directory
          cd /home/$VPS_USER/laravel_app || exit

          # Build and start services using docker-compose
          docker-compose up -d --build

          while ! docker-compose exec app curl -s http://localhost | grep -q "Welcome"; do
            echo "Waiting for the app to be ready..."
            sleep 5
          done
          
          # Run database migrations and seeds
          sudo docker-compose exec app php artisan migrate --force
          sudo docker-compose exec app php artisan db:seed

          # Clean up old Docker images
          docker image prune -f
          
        EOF
