name: Deploy Laravel to VPS Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy Laravel to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        # SSH vào VPS và thực hiện các lệnh
        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
        

          cd /home/$VPS_USER || exit

          # Clone repository
          git clone https://github.com/Quaniscoding/Library-management.git /home/$VPS_USER/laravel_app

          cd /home/$VPS_USER/laravel_app || exit

          # Cài đặt các dependency của Laravel
          composer install --no-interaction

          # Cấu hình file .env nếu cần
          cp .env.example .env
          php artisan key:generate

          # Dừng và xóa container cũ nếu có
          docker stop laravel_app || true
          docker rm laravel_app || true
          
          # Xây dựng lại Docker image (nếu cần)
          docker build -t laravel_app .

          # Run Laravel container và liên kết đến MySQL container đã có
          docker run --restart=always -d --name laravel_app --network laravel_network -p 8000:80 laravel_app

          # Dọn dẹp repository clone sau khi deploy
          cd ..
          rm -rf laravel_app
          docker image prune -f
        EOF
